### PR TITLE
Add Zoho SalesIQ script to head

### LINKED ISSUE #295: SalesIQ Tracking Installation
HI @vleong2332 - 

Can you please install the following code for us? Here are the instructions:

- SalesIQ helps you to track and analyze the visitors visiting your website and reports the info like the location of your visitors and shows you what page they are visiting, web actions performed on the website and much more.
- How to install this code on the website?
 - Copy the Visitor tracking code.In your website's source file, "paste" the code into the existing code anywhere before the </body> tag.
- "Save" and "Publish" the changes made to your website.

**Code**
<script type="text/javascript">
var $zoho=$zoho || {};$zoho.salesiq = $zoho.salesiq || {widgetcode:"587b877c0defdf8e751f0e57b85dfc45ae809f0bd6998ca30934ab343d15a54c", values:{},ready:function(){}};var d=document;s=d.createElement("script");s.type="text/javascript";s.id="zsiqscript";s.defer=true;s.src="https://salesiq.zoho.com/widget";t=d.getElementsByTagName("script")[0];t.parentNode.insertBefore(s,t);d.write("<div id='zsiqwidget'></div>");
</script>

### PR DESCRIPTION
**Pull request by vleong2332**
Resolves #295

### CODE REVIEW

**Comment by vleong2332** [comment]
@RassanGrant This adds the script to the head of every page. The script actually adds another `<script>` tag that pulls in another script from `salesiq.zoho.com`. Nothing blows up on this end, but I don't have a way to verify if it works on Zoho's end.

**Comment by RassanGrant** [comment]
@vleong2332 - I went ahead and merged this, will let you know once we start seeing salesiq reporting come online.

**Comment by vleong2332** [comment]
Alright. Let me know if this didn't work as intended.

**Comment by RassanGrant** [comment]
Hey @vleong2332 - Looks like this is pushing the chat box down to the bottom of the page. I just noticed you have this going to the head, but the instructions say that it should go before the closing of the body tag. Can you update it?

2018-07-23 12 04 50 pm

**Pull request merged**
